image_root: ./dataset/flickr/flickr_image
ann_root: ./dataset/flickr-TP/annotation_KeyboardAug/1/
dataset: flickr
pretrained: ./weights/blip/model_base_retrieval_flickr.pth
backbone: blip
vit: base
vit_ckpt_layer: 4
vit_grad_ckpt: true
image_size: 384
batch_size_image: 16
batch_size_text: 16
batch_size_total: 64
