image_root: ./dataset/CUHK-PEDES
ann_root: ''
dataset: cuhk_pedes
pretrained: ./weights/reid/irra_icfg_pedes.pth
backbone: clip_reid
vit: base
vit_ckpt_layer: 4
vit_grad_ckpt: true
image_size: 384
batch_size_image: 16
batch_size_text: 16
batch_size_total: 64
alpha: 0.4
k_test: 128
max_epoch: 1
min_lr: 0
negative_all_rank: false
queue_size: 57600
top_k_select: 5
weight_decay: 5e-4
